### PR TITLE
Personal mission num 4

### PR DESCRIPTION
**Pull request by OriAmir**
change the files by the instructions
@ItamarShDev @robi-y

### CODE REVIEW

**Comment by ItamarShDev** [comment]
missing two of the [original](https://github.com/jce-il/tdd-nodejs-find-a-person#the-actual-problem-add-a-feature-find-a-person) tests here

**Comment by OriAmir** [comment]
@ItamarShDev 
fix

**Comment by OriAmir** [comment]
@ItamarShDev fixed

**Comment by ItamarShDev** [comment]
:+1:

**Pull request closed without merging**
