### PR TITLE
Ex4 Submission

### PR DESCRIPTION
**Pull request by afek590**
@ItamarShDev 
@robi-y

### CODE REVIEW

**Comment by ItamarShDev** [comment]
i see none of the [original](https://github.com/jce-il/tdd-nodejs-find-a-person#the-actual-problem-add-a-feature-find-a-person) tests here

also,
please submit your work in the appropriate [doc](http://jce-il.github.io/se-class16b/assessments/#assessment-personal4-tdd)

**Comment by afek590** [comment]
@ItamarShDev 
updated according to your comments.

**Comment by ItamarShDev** [comment]
still didnt submit it...

**Comment by afek590** [comment]
@ItamarShDev 
how about now ?

**Comment by afek590** [comment]
@ItamarShDev 
?

**Comment by ItamarShDev** [comment]
:+1:

**Pull request closed without merging**
