### PR TITLE
Personal Mission 4

### PR DESCRIPTION
**Pull request by RoiZundak**
@ItamarShDev 
TDD Mission 
Added 3 function.

### CODE REVIEW

**Comment by RoiZundak** [comment]
@ItamarShDev @robi-y 
Can I get more info/reason for the X?

BR,
Roi C

**Comment by robi-y** [comment]
What X? from the CI? seems like a permission issue, I think can be ignored.

**Comment by RoiZundak** [comment]
image

**Comment by ItamarShDev** [comment]
[this](https://github.com/jce-il/tdd-nodejs-find-a-person/pull/6/commits/40d642c6173b7bee8f037d67245ca588b26b0e4b) is not a GREEN
 but nice job :+1:

**Pull request closed without merging**
