### PR TITLE
Ex4-Tdd

### PR DESCRIPTION
**Pull request by RubyLichtenstein**
@ItamarShDev

### CODE REVIEW

**Comment by ItamarShDev** [comment]
you didnt submit the work [here](http://jce-il.github.io/se-class16b/assessments/#assessment-personal4-tdd)

**Comment by RubyLichtenstein** [comment]
Done

**Comment by ItamarShDev** [comment]
you need to do [7](https://github.com/jce-il/tdd-nodejs-find-a-person#work-instructions) tests

**Comment by ItamarShDev** [comment]
:+1:

**Pull request closed without merging**
