### PR TITLE
TDD Assignment

### PR DESCRIPTION
**Pull request by talshi**
@ItamarShDev

### CODE REVIEW

**Comment by robi-y** [comment]
Hi,
Did you finish the exercise? please don't send the PR too early.
1. missing the RED stage commits
2. implementation passes all tests - which is good - but not complete yet, so you miss more tests.

**Comment by ItamarShDev** [comment]
also [submit](http://jce-il.github.io/se-class16b/assessments/#assessment-personal4-tdd) when you're done

**Comment by ItamarShDev** [comment]
@robi-y

**Comment by robi-y** [comment]
What's the status of this PR?

**Comment by ItamarShDev** [comment]
invalid
he did a different one and got graded for it

**Pull request closed without merging**
