### PR TITLE
EX4 submission

### PR DESCRIPTION
**Pull request by oronsa**
@ItamarShDev

### CODE REVIEW

**Comment by ItamarShDev** [comment]
:+1: 
next time please [add IDEA's Webstorm file to .gitignore](http://stackoverflow.com/questions/11968531/what-to-gitignore-from-the-idea-folder)

**Comment by ItamarShDev** [comment]
You didn't submitted the ex in the [doc](http://jce-il.github.io/se-class16b/assessments/#assessment-personal4-tdd)

**Comment by oronsa** [comment]
oops, I will fix it now

2016-05-23 10:47 GMT+03:00 itamar sharify notifications@github.com:

**Comment by ItamarShDev** [comment]
:+1:

**Pull request closed without merging**
