### PR TITLE
ex04-se

### PR DESCRIPTION
**Pull request by alonshmilo**
This is ex04 for se class

### CODE REVIEW

**Comment by ItamarShDev** [comment]
alon,
your tests are worthless if you just return true or false in each function not matter its job
for example: map inconsistencies should  check if you have same person more than once, 
but if im not mistaken, you just returned true and false?

**Comment by alonshmilo** [comment]
Ok, I have implemented this exercise as I understand from other students who did it that way. To present it again until midnight? @ItamarShDev

**Comment by alonshmilo** [comment]
@ItamarShDev Hi, I have changed the map file so that the tests will be accurate.

**Comment by ItamarShDev** [comment]
:+1:

**Pull request closed without merging**
